// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/21/2024, 8:58:42 AM
const configMerger = require("/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/plugins/**/*.{js,ts,mjs}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/composables/**/*.{js,ts,mjs}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/utils/**/*.{js,ts,mjs}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/nayla/pweb-fp-P18-2024/frontend/finalproject-p18/app.config.{js,ts,mjs}"] } }));

module.exports = config
